# Generated by Django 3.2.6 on 2021-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_pontoturistico_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ManyToManyField(to='enderecos.Endereco'),
        ),
    ]
